if(DEFINED RTSL_EMBED_INPUTS AND DEFINED RTSL_EMBED_OUTPUT)
    string(REPLACE "\\;" ";" RTSL_EMBED_INPUTS "${RTSL_EMBED_INPUTS}")
    string(REPLACE "\\;" ";" RTSL_EMBED_SYMBOLS "${RTSL_EMBED_SYMBOLS}")

    set(_rtsl_embed_temporary_output "${RTSL_EMBED_OUTPUT}.tmp")
    file(WRITE "${_rtsl_embed_temporary_output}" "#include <rtsl/program.hpp>\n#include <cstdint>\n")

    set(_rtsl_index 0)
    foreach(input_path IN LISTS RTSL_EMBED_INPUTS)
        list(GET RTSL_EMBED_SYMBOLS "${_rtsl_index}" symbol_name)
        if(NOT symbol_name)
            get_filename_component(input_name "${input_path}" NAME_WE)
            set(symbol_name "${input_name}_rtslp")
        endif()
        math(EXPR _rtsl_index "${_rtsl_index} + 1")

        file(READ "${input_path}" _hex HEX)
        file(APPEND "${_rtsl_embed_temporary_output}" "alignas(16) const std::uint8_t ${symbol_name}_data[]={\n")

        string(LENGTH "${_hex}" _hex_length)
        math(EXPR _byte_count "${_hex_length} / 2")
        if(_byte_count GREATER 0)
            math(EXPR _last_index "${_byte_count} - 1")
            foreach(index RANGE 0 "${_last_index}")
                math(EXPR _offset "${index} * 2")
                math(EXPR _next_index "${index} + 1")
                math(EXPR _column "${_next_index} % 12")
                string(SUBSTRING "${_hex}" "${_offset}" 2 _byte)
                if(_next_index EQUAL _byte_count)
                    file(APPEND "${_rtsl_embed_temporary_output}" "0x${_byte}\n")
                elseif(_column EQUAL 0)
                    file(APPEND "${_rtsl_embed_temporary_output}" "0x${_byte},\n")
                else()
                    file(APPEND "${_rtsl_embed_temporary_output}" "0x${_byte},")
                endif()
            endforeach()
        endif()

        file(APPEND "${_rtsl_embed_temporary_output}" "};\n")
        file(APPEND "${_rtsl_embed_temporary_output}" "extern \"C\" const rtsl::ProgramBytes ${symbol_name} = {\n")
        file(APPEND "${_rtsl_embed_temporary_output}" "    ${symbol_name}_data,\n")
        file(APPEND "${_rtsl_embed_temporary_output}" "    sizeof(${symbol_name}_data)\n")
        file(APPEND "${_rtsl_embed_temporary_output}" "};\n\n")
    endforeach()

    file(RENAME "${_rtsl_embed_temporary_output}" "${RTSL_EMBED_OUTPUT}" RESULT _rtsl_embed_rename_result)
    if(NOT _rtsl_embed_rename_result STREQUAL "0")
        message(FATAL_ERROR "Failed to publish RTSL embed '${RTSL_EMBED_OUTPUT}': ${_rtsl_embed_rename_result}")
    endif()
endif()
