if(NOT DEFINED RTSL_EMBED_INPUTS OR NOT DEFINED RTSL_EMBED_OUTPUT OR NOT DEFINED RTSL_EMBED_NAMESPACE)
    message(FATAL_ERROR "RtslEmbed.cmake requires RTSL_EMBED_INPUTS, RTSL_EMBED_OUTPUT, and RTSL_EMBED_NAMESPACE")
endif()

file(WRITE "${RTSL_EMBED_OUTPUT}" "#include <cstddef>\n#include <cstdint>\n\n")

string(REPLACE ";" "\n" input_list "${RTSL_EMBED_INPUTS}")
foreach(input_path IN LISTS RTSL_EMBED_INPUTS)
    get_filename_component(input_name "${input_path}" NAME_WE)
    file(READ "${input_path}" _hex HEX)
    string(REPLACE "" ";" _hex_bytes "${_hex}")
    list(TRANSFORM _hex_bytes TOUPPER)

    file(APPEND "${RTSL_EMBED_OUTPUT}" "namespace ${RTSL_EMBED_NAMESPACE} {\n")
    file(APPEND "${RTSL_EMBED_OUTPUT}" "alignas(16) const std::uint8_t ${input_name}_rtslp[] = {\n")

    set(_line "")
    set(_count 0)
    foreach(byte IN LISTS _hex_bytes)
        string(APPEND _line "0x${byte}, ")
        math(EXPR _count "${_count} + 1")
        if(_count EQUAL 12)
            file(APPEND "${RTSL_EMBED_OUTPUT}" "    ${_line}\n")
            set(_line "")
            set(_count 0)
        endif()
    endforeach()
    if(NOT _line STREQUAL "")
        file(APPEND "${RTSL_EMBED_OUTPUT}" "    ${_line}\n")
    endif()

    file(APPEND "${RTSL_EMBED_OUTPUT}" "};\n")
    file(APPEND "${RTSL_EMBED_OUTPUT}" "constexpr std::size_t ${input_name}_rtslp_size = sizeof(${input_name}_rtslp);\n")
    file(APPEND "${RTSL_EMBED_OUTPUT}" "}\n\n")
endforeach()
